# Generated by Django 4.2.17 on 2025-02-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_id', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('test_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=20)),
                ('execution_date', models.DateField()),
                ('project_name', models.CharField(max_length=100)),
            ],
        ),
    ]
