# Generated by Django 4.2.17 on 2025-02-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('detail', models.TextField(blank=True, null=True)),
                ('company_paid', models.CharField(choices=[('Checked', 'Checked'), ('Unchecked', 'Unchecked')], max_length=10)),
                ('currency_code', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_exchange_rate', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exchange_override', models.CharField(blank=True, max_length=20, null=True)),
                ('expense_location', models.CharField(max_length=50)),
                ('total_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project_code', models.CharField(max_length=20)),
                ('project_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='TestCase',
        ),
    ]
