# Generated by Django 5.1.3 on 2025-03-09 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CardData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_exchange_rate",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("exchange_override", models.CharField(max_length=50)),
                (
                    "currency_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="card_data.currency",
                    ),
                ),
                (
                    "location_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="card_data.location",
                    ),
                ),
            ],
        ),
    ]
