# Generated by Django 3.2.25 on 2025-03-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddata',
            name='card_no',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
