version: '3.8'

services:
  web:
    build: .
    working_dir: /app/backend
    command: python manage.py runserver 0.0.0.0:${PORT}
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env