# Generated by Django 4.2.17 on 2025-01-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_inputs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
    ]
