# Generated by Django 5.1.3 on 2025-03-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_expense_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
