# Generated by Django 5.1.3 on 2025-03-13 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("card_data", "0001_initial"),
        ("expenses", "0005_alter_expense_currency_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="location_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="card_data.location",
            ),
        ),
    ]
