# Generated by Django 4.2.17 on 2025-02-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('merchant', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('receipt_file', models.FileField(upload_to='receipts/')),
            ],
        ),
    ]
