# Generated by Django 5.1.5 on 2025-03-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('detail', models.CharField(max_length=1000)),
                ('company_paid', models.CharField(max_length=200)),
                ('currency_code', models.CharField(max_length=3)),
                ('amount', models.FloatField()),
                ('exchange_rate', models.FloatField()),
                ('location', models.CharField(max_length=200)),
                ('tax_amount', models.FloatField()),
                ('net_amount', models.FloatField()),
                ('project_name', models.CharField(max_length=200)),
            ],
        ),
    ]
